import 'course_models.dart';

class MockCoursesData {
  static List<LmsCourse> courses = [
    // Course 1: CIT Prep
    LmsCourse(
      id: 'course-cit',
      title: 'CIT Prep - Certified Instructional Trainer',
      category: 'Professional Certification',
      level: 'Advanced',
      thumbnailUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&auto=format&fit=crop&q=80',
      rating: 4.9,
      ratingCount: 342,
      studentsCount: 1280,
      progress: 0.68,
      instructorName: 'Dr. John Doe, CIT Master',
      instructorRole: 'Lead Instructor & Board Certified Trainer',
      instructorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      instructorEmail: 'john.doe@hexalabes.com',
      duration: '45 Hours',
      modulesCount: 4,
      lecturesCount: 16,
      isCertified: true,
      hasScorm: true,
      courseFee: 45000,
      isEnrolled: true,
      description:
          'Comprehensive preparation for the Board of Certified Safety Professionals (BCSP) Certified Instructional Trainer (CIT) examination. Covers adult learning theory, training needs assessment, curriculum design, classroom delivery, and instructional evaluation.',
      whatYouWillLearn: [
        'Adult learning principles and instructional design methodologies',
        'Effective presentation techniques and interactive training delivery',
        'Designing valid assessments, rubrics, and feedback mechanisms',
        'Interactive SCORM 1.2 digital simulations and digital learning tools',
        'Full mock exams aligned with BCSP CIT blueprint guidelines',
      ],
      requirements: [
        'Basic familiarity with instructional design or corporate training',
        'No prior certification required, open to all safety and education professionals',
      ],
      resources: [
        LmsResource(
          id: 'res-cit-1',
          title: 'CIT Exam Blueprint & Reference Guide 2026',
          type: 'PDF',
          fileSize: '4.8 MB',
          pages: 64,
          description: 'Official BCSP CIT Examination blueprint with domain percentages and sample question types.',
          previewText:
              'DOMAIN 1: Training Needs Assessment and Analysis (22%)\nDOMAIN 2: Instructional Development and Design (28%)\nDOMAIN 3: Training Delivery and Facilitation (32%)\nDOMAIN 4: Evaluation and Assessment (18%)\n\nKey Concepts:\n- Andragogy vs Pedagogy\n- Blooms Taxonomy for Cognitive Domain\n- Kirkpatricks Four-Level Evaluation Model',
        ),
        LmsResource(
          id: 'res-cit-2',
          title: 'Adult Learning Theories & Andragogy Handout',
          type: 'Study Material',
          fileSize: '2.4 MB',
          pages: 32,
          description: 'In-depth notes on Malcolm Knowles adult learning assumptions and experiential learning cycles.',
          previewText:
              'Malcolm Knowles identified 6 core assumptions about adult learners:\n1. Need to Know: Adults need to understand why they must learn something.\n2. Self-Concept: Adults have a self-concept of being responsible for their decisions.\n3. Prior Experience: Adult learners bring diverse life experience to training.\n4. Readiness to Learn: Adults become ready to learn when they experience a need to cope.\n5. Orientation to Learning: Life-centered, task-centered, or problem-centered.\n6. Motivation: Internal motivators (self-esteem, job satisfaction) dominate.',
        ),
        LmsResource(
          id: 'res-cit-3',
          title: 'Instructional Design Presentation Slides',
          type: 'Presentation',
          fileSize: '12.1 MB',
          pages: 45,
          description: 'Slide deck covering ADDIE model and rapid instructional prototyping.',
          previewText: 'Slide 1: Overview of ADDIE Model (Analysis, Design, Development, Implementation, Evaluation)\nSlide 2: Conducting Needs Analysis\nSlide 3: Writing SMART Learning Objectives\nSlide 4: Formative vs Summative Evaluation',
        ),
      ],
      discussions: [
        LmsDiscussion(
          id: 'disc-cit-1',
          studentName: 'Khalid Ahmed',
          studentAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
          date: '2 days ago',
          topic: 'Module 2: Blooms Taxonomy in Safety Exams',
          question: 'In the CIT exam, how does BCSP distinguish between Analyze and Evaluate level questions for emergency protocols?',
          upvotes: 8,
          answers: [
            DiscussionAnswer(
              id: 'ans-1',
              authorName: 'Dr. John Doe, CIT Master',
              isInstructor: true,
              date: '1 day ago',
              answerText:
                  'Great question Khalid! Analyze level questions test your ability to break down incident reports into root causes. Evaluate questions require you to make a judgment between competing corrective action plans based on OSHA criteria.',
              upvotes: 12,
            ),
          ],
        ),
        LmsDiscussion(
          id: 'disc-cit-2',
          studentName: 'Zainab Malik',
          studentAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
          date: '3 days ago',
          topic: 'Module 3: SCORM completion score requirement',
          question: 'Do we need 80% or 70% in the interactive SCORM simulation to unlock the final assessment test?',
          upvotes: 4,
          answers: [
            DiscussionAnswer(
              id: 'ans-2',
              authorName: 'Dr. John Doe, CIT Master',
              isInstructor: true,
              date: '2 days ago',
              answerText: 'The SCORM interactive simulation requires at least 75% score across the 4 interactive checkpoints to achieve full completion status.',
              upvotes: 6,
            ),
          ],
        ),
      ],
      modules: [
        LmsModule(
          id: 'cit-mod-1',
          courseId: 'course-cit',
          moduleNumber: 1,
          title: 'Adult Learning Theory & Training Assessment',
          description: 'Understanding adult learner psychology, learning styles, and conducting organizational needs assessments.',
          duration: '10 Hours',
          isUnlocked: true,
          progress: 1.0,
          resources: [
            LmsResource(
              id: 'cit-m1-r1',
              title: 'Module 1 Study Guide',
              type: 'PDF',
              fileSize: '1.8 MB',
              pages: 20,
              description: 'Comprehensive study guide for adult learning principles and needs assessment.',
              previewText: 'Key topics: Needs Assessment surveys, Gap Analysis, Malcolm Knowles andragogical model.',
            ),
          ],
          quizzes: [
            LmsQuizRef(
              id: 'cit-quiz-1',
              title: 'Module 1 Checkpoint Quiz',
              questionCount: 15,
              timeLimitMinutes: 20,
              passingScore: 75,
              isCompleted: true,
              userScore: 93,
            ),
          ],
          assessmentTest: LmsAssessmentRef(
            id: 'cit-asst-1',
            title: 'Module 1 Comprehensive Assessment',
            totalMarks: 50,
            timeLimitMinutes: 45,
            dueDate: '2026-10-15',
            isUnlocked: true,
            isSubmitted: true,
            scoredMarks: 47,
          ),
          lectures: [
            LmsLecture(
              id: 'cit-lec-101',
              moduleId: 'cit-mod-1',
              lectureNumber: 1,
              title: 'Introduction to CIT & Certification Standards',
              duration: '22 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Welcome to the CIT certification course. In this video, we review BCSP standards, examination blueprints, and exam day requirements.',
              transcript: 'Hello everyone and welcome to the Certified Instructional Trainer preparation course. In this initial lecture we establish our foundational roadmap...',
              notes: [
                LectureNote(id: 'n1', timestamp: '04:15', content: 'BCSP requires recertification every 5 years.', createdAt: DateTime.now().subtract(const Duration(days: 3))),
              ],
              resources: [],
            ),
            LmsLecture(
              id: 'cit-lec-102',
              moduleId: 'cit-mod-1',
              lectureNumber: 2,
              title: 'Malcolm Knowles Andragogy vs Pedagogy',
              duration: '28 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Core principles of adult learning: self-direction, experience integration, problem-oriented learning.',
              transcript: 'Adult learners possess intrinsic motivation and rely on accumulated experience. Pedagogical methods do not transfer directly to corporate classrooms...',
              notes: [],
              resources: [],
            ),
            LmsLecture(
              id: 'cit-lec-103',
              moduleId: 'cit-mod-1',
              lectureNumber: 3,
              title: 'Conducting Training Needs Assessment (TNA)',
              duration: '35 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Techniques for identifying knowledge gaps, organizational performance metrics, and compliance mandates.',
              transcript: 'Training Needs Assessment involves three levels: Organizational Analysis, Task Analysis, and Individual Person Analysis...',
              notes: [],
              resources: [],
            ),
          ],
        ),

        // Module 2: Instructional Design
        LmsModule(
          id: 'cit-mod-2',
          courseId: 'course-cit',
          moduleNumber: 2,
          title: 'Instructional Design & Course Development',
          description: 'Writing behavioral objectives, structuring curriculum, developing multimedia handouts, and lesson planning.',
          duration: '12 Hours',
          isUnlocked: true,
          progress: 0.75,
          scormPackage: LmsScormPackage(
            id: 'scorm-cit-mod2',
            title: 'Interactive SCORM 1.2: Instructional Design Simulation',
            description: 'Interactive SCORM module covering ADDIE phases, Blooms taxonomy selector, and course prototyping.',
            status: 'In Progress',
            score: 80.0,
            currentChapterIndex: 1,
            chapters: [
              ScormChapter(
                title: 'Chapter 1: The ADDIE Framework in Practice',
                content:
                    'The ADDIE instructional design framework provides a systematic approach to instructional course creation. It consists of Analysis, Design, Development, Implementation, and Evaluation phases.',
                keyPoints: [
                  'Analysis identifies audience and learning constraints',
                  'Design establishes learning objectives and assessment plans',
                  'Development creates courseware and instructional media',
                  'Implementation delivers training in live or digital format',
                  'Evaluation measures outcomes using Kirkpatricks 4 levels',
                ],
                quizQuestion: 'Which phase of ADDIE produces the detailed lesson plan and storyboard?',
                quizOptions: ['Analysis Phase', 'Design Phase', 'Implementation Phase', 'Evaluation Phase'],
                correctAnswerIndex: 1,
                explanation: 'The Design phase focuses on learning objectives, assessment instruments, exercises, content, and lesson planning.',
              ),
              ScormChapter(
                title: 'Chapter 2: Writing Measurable Learning Objectives',
                content:
                    'Effective learning objectives must be specific, measurable, achievable, relevant, and time-bound (SMART). Use Blooms revised taxonomy action verbs.',
                keyPoints: [
                  'Avoid vague verbs like "know" or "understand"',
                  'Use observable verbs: "demonstrate", "calculate", "analyze", "inspect"',
                  'Condition, Behavior, and Standard criteria (Mager Model)',
                ],
                quizQuestion: 'Which of the following is a properly formatted SMART behavioral objective?',
                quizOptions: [
                  'The student will understand safety regulations.',
                  'Given a digital multimeter, the trainee will measure circuit voltage within 2% accuracy in 5 minutes.',
                  'The student will appreciate the importance of PPE.',
                  'The trainee will know fire extinguisher classifications.'
                ],
                correctAnswerIndex: 1,
                explanation: 'This objective includes given condition (multimeter), observable behavior (measure voltage), and measurable standard (2% accuracy, 5 mins).',
              ),
              ScormChapter(
                title: 'Chapter 3: Interactive Media & Classroom Simulations',
                content:
                    'Multimedia learning principles dictate that students learn more deeply from words and pictures than from words alone (Dual-Coding Theory).',
                keyPoints: [
                  'Coherence Principle: Exclude extraneous words and audio',
                  'Contiguity Principle: Place corresponding words and graphics near each other',
                  'Signaling Principle: Highlight essential material and cues',
                ],
                quizQuestion: 'According to Mayers Multimedia Principles, what is the Modality Principle?',
                quizOptions: [
                  'Students learn better from graphics and narration than graphics and on-screen text.',
                  'Students learn better when lessons are short.',
                  'Students learn better without pictures.',
                  'Students learn better in quiet rooms.'
                ],
                correctAnswerIndex: 0,
                explanation: 'The Modality Principle states that visual graphics paired with spoken audio prevents cognitive overload of the visual channel.',
              ),
              ScormChapter(
                title: 'Chapter 4: Formative vs Summative Assessment Checks',
                content:
                    'Formative assessments monitor student learning to provide ongoing feedback that instructors can use to improve their teaching. Summative assessments evaluate learning at the end of an instructional unit.',
                keyPoints: [
                  'Formative: In-class polls, quick quizzes, 1-minute reflection papers',
                  'Summative: Final exams, capstone projects, board certification tests',
                  'Kirkpatrick Level 2 evaluates knowledge acquisition through testing',
                ],
                quizQuestion: 'A mid-lecture interactive quiz that allows the instructor to adjust pacing is what kind of assessment?',
                quizOptions: ['Summative Assessment', 'Formative Assessment', 'Diagnostic Assessment', 'Norm-referenced Test'],
                correctAnswerIndex: 1,
                explanation: 'Formative assessments occur during instruction to provide rapid feedback and guide teaching.',
              ),
            ],
          ),
          resources: [
            LmsResource(
              id: 'cit-m2-r1',
              title: 'Blooms Taxonomy Action Verbs Quick Reference',
              type: 'Handout',
              fileSize: '1.2 MB',
              pages: 4,
              description: 'Chart of action verbs categorized across all 6 cognitive domain levels.',
              previewText: 'Remembering: Define, list, recall\nUnderstanding: Classify, describe, explain\nApplying: Demonstrate, implement, solve\nAnalyzing: Differentiate, organize, relate\nEvaluating: Appraise, defend, judge\nCreating: Assemble, construct, design.',
            ),
          ],
          quizzes: [
            LmsQuizRef(
              id: 'cit-quiz-2',
              title: 'Instructional Design Mastery Quiz',
              questionCount: 20,
              timeLimitMinutes: 25,
              passingScore: 80,
              isCompleted: true,
              userScore: 88,
            ),
          ],
          assessmentTest: LmsAssessmentRef(
            id: 'cit-asst-2',
            title: 'Module 2 Assessment Test: Lesson Plan Design',
            totalMarks: 50,
            timeLimitMinutes: 60,
            dueDate: '2026-10-20',
            isUnlocked: true,
            isSubmitted: false,
          ),
          lectures: [
            LmsLecture(
              id: 'cit-lec-201',
              moduleId: 'cit-mod-2',
              lectureNumber: 1,
              title: 'The ADDIE Model for Training Programs',
              duration: '32 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Deep dive into every phase of ADDIE and how corporate safety programs utilize iterative prototyping.',
              transcript: 'Today we break down the five phases of the ADDIE process. Analysis starts with defining performance discrepancies...',
              notes: [
                LectureNote(id: 'n2', timestamp: '12:40', content: 'Design phase includes storyboard and assessment blueprint.', createdAt: DateTime.now().subtract(const Duration(days: 1))),
              ],
              resources: [],
            ),
            LmsLecture(
              id: 'cit-lec-202',
              moduleId: 'cit-mod-2',
              lectureNumber: 2,
              title: 'Applying Blooms Taxonomy to Safety Objectives',
              duration: '26 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'How to write measurable objectives using the Mager 3-part format (Behavior, Condition, Standard).',
              transcript: 'A measurable objective must never use subjective terms like "be aware of". Instead specify observable physical or cognitive actions...',
              notes: [],
              resources: [],
            ),
            LmsLecture(
              id: 'cit-lec-203',
              moduleId: 'cit-mod-2',
              lectureNumber: 3,
              title: 'Developing Engaging Handouts & Media',
              duration: '24 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?w=500&auto=format&fit=crop&q=80',
              isCompleted: false,
              overview: 'Formatting visual aids, avoiding cognitive overload, and utilizing digital SCORM 1.2 modules.',
              transcript: 'When designing presentation slides, the 6x6 rule keeps cognitive load manageable: no more than 6 bullet points with 6 words each...',
              notes: [],
              resources: [],
            ),
          ],
        ),

        // Module 3: Training Delivery
        LmsModule(
          id: 'cit-mod-3',
          courseId: 'course-cit',
          moduleNumber: 3,
          title: 'Training Delivery, Facilitation & Classroom Management',
          description: 'Mastering presentation skills, handling difficult questions, small group exercises, and virtual classroom delivery.',
          duration: '11 Hours',
          isUnlocked: true,
          progress: 0.33,
          resources: [
            LmsResource(
              id: 'cit-m3-r1',
              title: 'Classroom Facilitation & Body Language Checklist',
              type: 'PDF',
              fileSize: '3.1 MB',
              pages: 18,
              description: 'Techniques for instructor posture, vocal modulation, eye contact, and active questioning.',
              previewText: 'Voice modulation tips:\n- Pitch variation prevents monotony\n- Intentional pauses build suspense before key safety rules\n- Eye contact: 3-5 seconds per participant.',
            ),
          ],
          quizzes: [
            LmsQuizRef(
              id: 'cit-quiz-3',
              title: 'Delivery & Facilitation Quiz',
              questionCount: 15,
              timeLimitMinutes: 20,
              passingScore: 75,
              isCompleted: false,
            ),
          ],
          assessmentTest: LmsAssessmentRef(
            id: 'cit-asst-3',
            title: 'Module 3 Assessment Test: Micro-Teaching Video',
            totalMarks: 50,
            timeLimitMinutes: 60,
            dueDate: '2026-10-28',
            isUnlocked: true,
            isSubmitted: false,
          ),
          lectures: [
            LmsLecture(
              id: 'cit-lec-301',
              moduleId: 'cit-mod-3',
              lectureNumber: 1,
              title: 'Vocal Dynamics, Body Language & Platform Presence',
              duration: '30 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Techniques for command of the classroom, active listening, and managing presentation anxiety.',
              transcript: 'Body language accounts for over half of perceived confidence in a classroom setting...',
              notes: [],
              resources: [],
            ),
            LmsLecture(
              id: 'cit-lec-302',
              moduleId: 'cit-mod-3',
              lectureNumber: 2,
              title: 'Facilitating Small Group Case Studies & Roleplay',
              duration: '27 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1531497865144-0464ef8fb9a9?w=500&auto=format&fit=crop&q=80',
              isCompleted: false,
              overview: 'Structuring group dynamics, debriefing exercises, and maximizing experiential takeaways.',
              transcript: 'Small group facilitation requires clear timekeeping and assigned roles (facilitator, scribe, timekeeper, spokesperson)...',
              notes: [],
              resources: [],
            ),
          ],
        ),

        // Module 4: Evaluation & Continuous Improvement
        LmsModule(
          id: 'cit-mod-4',
          courseId: 'course-cit',
          moduleNumber: 4,
          title: 'Evaluation, Assessment & Continuous Improvement',
          description: 'Kirkpatricks 4-level evaluation, return on investment (ROI) calculations, item analysis for test questions.',
          duration: '12 Hours',
          isUnlocked: true,
          progress: 0.0,
          resources: [
            LmsResource(
              id: 'cit-m4-r1',
              title: 'Kirkpatrick 4-Level Evaluation Toolkit',
              type: 'PDF',
              fileSize: '2.9 MB',
              pages: 24,
              description: 'Survey templates, pre/post test design, and behavioral audit checklists.',
              previewText: 'Level 1: Reaction (Did they like it?)\nLevel 2: Learning (Did they understand it?)\nLevel 3: Behavior (Do they apply it at work?)\nLevel 4: Results (Did safety metrics improve?).',
            ),
          ],
          quizzes: [
            LmsQuizRef(
              id: 'cit-quiz-4',
              title: 'Evaluation & Test Item Analysis Quiz',
              questionCount: 20,
              timeLimitMinutes: 30,
              passingScore: 80,
              isCompleted: false,
            ),
          ],
          assessmentTest: LmsAssessmentRef(
            id: 'cit-asst-4',
            title: 'Final Capstone Assessment & Mock CIT Exam',
            totalMarks: 100,
            timeLimitMinutes: 120,
            dueDate: '2026-11-05',
            isUnlocked: true,
            isSubmitted: false,
          ),
          lectures: [
            LmsLecture(
              id: 'cit-lec-401',
              moduleId: 'cit-mod-4',
              lectureNumber: 1,
              title: 'Kirkpatricks Four Levels of Training Evaluation',
              duration: '35 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=500&auto=format&fit=crop&q=80',
              isCompleted: false,
              overview: 'Measuring Reaction, Learning, Behavior, and Organizational Business Results.',
              transcript: 'Donald Kirkpatrick revolutionized training assessment by establishing that participant satisfaction alone is insufficient to demonstrate training efficacy...',
              notes: [],
              resources: [],
            ),
            LmsLecture(
              id: 'cit-lec-402',
              moduleId: 'cit-mod-4',
              lectureNumber: 2,
              title: 'Test Reliability, Validity & Question Item Analysis',
              duration: '31 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=500&auto=format&fit=crop&q=80',
              isCompleted: false,
              overview: 'Calculating discrimination index, distractor analysis, and building statistically valid test banks.',
              transcript: 'Item analysis allows us to verify if an exam question accurately differentiates high performers from struggling students...',
              notes: [],
              resources: [],
            ),
          ],
        ),
      ],
    ),

    // Course 2: IOSH Managing Safely
    LmsCourse(
      id: 'course-iosh',
      title: 'IOSH Managing Safely V5.0',
      category: 'Health & Safety Management',
      level: 'Intermediate',
      thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
      rating: 4.85,
      ratingCount: 210,
      studentsCount: 890,
      progress: 0.85,
      instructorName: 'Sarah Jenkins, CMIOSH',
      instructorRole: 'Chartered Safety Consultant',
      instructorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
      instructorEmail: 'sarah.jenkins@hexalabes.com',
      duration: '30 Hours',
      modulesCount: 7,
      lecturesCount: 24,
      isCertified: true,
      hasScorm: true,
      courseFee: 38000,
      isEnrolled: true,
      description:
          'Globally recognized certificate by the Institution of Occupational Safety and Health (IOSH). Designed for managers and supervisors in any sector to understand practical actions required to handle health and safety in their teams.',
      whatYouWillLearn: [
        'Assessing and controlling risks in workplace environments',
        'Understanding manager health & safety legal responsibilities',
        'Identifying common hazards (Fire, Electricity, Chemicals, Work at Height)',
        'Investigating accidents and incidents to prevent reoccurrence',
        'Measuring health and safety performance with leading/lagging indicators',
      ],
      requirements: ['No previous health and safety knowledge required.'],
      resources: [
        LmsResource(
          id: 'res-iosh-1',
          title: 'IOSH Managing Safely V5.0 Course Book PDF',
          type: 'Book',
          fileSize: '18.4 MB',
          pages: 140,
          description: 'Official comprehensive study text for IOSH Managing Safely.',
          previewText: 'Module 1: Introducing Managing Safely\nModule 2: Assessing Risks\nModule 3: Controlling Risks\nModule 4: Understanding Responsibilities\nModule 5: Understanding Hazards\nModule 6: Investigating Incidents\nModule 7: Measuring Performance.',
        ),
      ],
      discussions: [],
      modules: [
        LmsModule(
          id: 'iosh-mod-1',
          courseId: 'course-iosh',
          moduleNumber: 1,
          title: 'Introducing Managing Safely & Risk Assessment',
          description: 'The moral, legal, and financial reasons for managing safety and the 5-step risk assessment method.',
          duration: '6 Hours',
          isUnlocked: true,
          progress: 1.0,
          resources: [],
          quizzes: [
            LmsQuizRef(
              id: 'iosh-quiz-1',
              title: 'Risk Assessment Quiz',
              questionCount: 10,
              timeLimitMinutes: 15,
              passingScore: 80,
              isCompleted: true,
              userScore: 100,
            ),
          ],
          lectures: [
            LmsLecture(
              id: 'iosh-lec-1',
              moduleId: 'iosh-mod-1',
              lectureNumber: 1,
              title: 'The Moral, Legal & Financial Case for Safety',
              duration: '20 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Why managers must manage health and safety: moral duty of care, criminal/civil legal penalties, and direct/indirect accident costs.',
              transcript: 'Health and safety management starts with understanding the three main drivers: Moral, Legal, and Financial reasons...',
              notes: [],
              resources: [],
            ),
          ],
        ),
      ],
    ),

    // Course 3: Web Development
    LmsCourse(
      id: 'course-webdev',
      title: 'Web Development (Full Stack MERN)',
      category: 'Computer Science & Software',
      level: 'All Levels',
      thumbnailUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&auto=format&fit=crop&q=80',
      rating: 4.92,
      ratingCount: 512,
      studentsCount: 2340,
      progress: 0.72,
      instructorName: 'Engr. M. Farooq',
      instructorRole: 'Principal Full Stack Architect',
      instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      instructorEmail: 'farooq@hexalabes.com',
      duration: '60 Hours',
      modulesCount: 16,
      lecturesCount: 48,
      isCertified: true,
      hasScorm: false,
      courseFee: 40000,
      isEnrolled: true,
      description: 'Master modern frontend and backend web development using React, Node.js, Express, MongoDB, RESTful APIs, and deployment pipelines.',
      whatYouWillLearn: [
        'Responsive UI Design with HTML5, Modern CSS, Grid & Tailwind',
        'Modern JavaScript (ES6+, Async/Await, Closures, DOM)',
        'React 18 Architecture: Hooks, Redux Toolkit, Context API',
        'Backend Development with Node.js, Express, and JWT Authentication',
        'Database design with MongoDB, Mongoose ORM, and SQL queries',
      ],
      requirements: ['Basic computer literacy. No programming experience required.'],
      resources: [],
      discussions: [],
      modules: [
        LmsModule(
          id: 'wd-mod-1',
          courseId: 'course-webdev',
          moduleNumber: 1,
          title: 'Modern Frontend Fundamentals (HTML5 & Modern CSS)',
          description: 'Semantic markup, Flexbox, Grid systems, and building responsive portfolio layouts.',
          duration: '8 Hours',
          isUnlocked: true,
          progress: 1.0,
          resources: [],
          quizzes: [],
          lectures: [
            LmsLecture(
              id: 'wd-lec-1',
              moduleId: 'wd-mod-1',
              lectureNumber: 1,
              title: 'HTML5 Semantic Tags & Accessibility Best Practices',
              duration: '25 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Structure web pages with header, nav, main, section, article, and footer tags.',
              transcript: 'In this lecture we explore semantic HTML5 elements that improve SEO and accessibility for screen readers...',
              notes: [],
              resources: [],
            ),
          ],
        ),
      ],
    ),
  ];

  static LmsCourse getCourseById(String id) {
    return courses.firstWhere(
      (c) => c.id == id,
      orElse: () => courses.first,
    );
  }
}
