import 'course_models.dart';

class MockCoursesData {
  static List<LmsCourse> courses = [
    // Course 1: IELTS Academic Preparation (Matching LMS Course Modules Screenshot)
    LmsCourse(
      id: 'course-ielts',
      title: 'IELTS Academic Preparation',
      category: 'Language & Communication',
      level: 'All Levels',
      thumbnailUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&auto=format&fit=crop&q=80',
      rating: 4.95,
      ratingCount: 680,
      studentsCount: 3420,
      progress: 0.65,
      instructorName: 'Madam Ayesha Khan',
      instructorRole: 'Lead IELTS Master Trainer & British Council Certified',
      instructorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
      instructorEmail: 'ayesha.khan@hexalabes.com',
      duration: '40 Hours',
      modulesCount: 4,
      lecturesCount: 20,
      isCertified: true,
      hasScorm: false,
      courseFee: 25000,
      isEnrolled: true,
      description:
          'Comprehensive IELTS Academic mastery covering all 4 modules: Reading, Listening, Writing (Task 1 & Task 2), and Speaking. Includes authentic Cambridge mock tests, band 9 vocabulary, and expert assessment rubrics.',
      whatYouWillLearn: [
        'Mastering skim, scan and speed reading techniques for IELTS Academic Reading',
        'Active listening strategies for diverse British, American, and Australian accents',
        'Band 9 essay structures, linking phrases, and Task 1 graph/chart report templates',
        'Fluency, lexical resource, and idiomatic speech for IELTS Speaking Part 1, 2, and 3',
        'Full authentic timed mock exams with detailed band score feedback',
      ],
      requirements: [
        'Intermediate level English comprehension (B1/B2 level recommended)',
        'Dedication to daily reading, listening practice, and writing assignments',
      ],
      resources: [
        LmsResource(
          id: 'res-ielts-1',
          title: 'Book Two',
          type: 'Book',
          fileSize: '14.2 MB',
          pages: 180,
          description: 'Official Cambridge IELTS Practice Tests Book 2 with full answer keys, transcripts, and model essays.',
          previewText:
              'CAMBRIDGE IELTS PRACTICE TESTS - BOOK TWO\n\nTest 1: Reading Passages 1-3 (Academic)\nTest 1: Listening Sections 1-4 with audio script\nTest 1: Writing Task 1 Report & Task 2 Opinion Essay\nTest 1: Speaking Topics & Cue Cards\n\nBand Descriptors & Scoring Criteria Included.',
        ),
        LmsResource(
          id: 'res-ielts-2',
          title: 'IELTS Books',
          type: 'Book',
          fileSize: '32.5 MB',
          pages: 350,
          description: 'Complete British Council & Cambridge reference library covering grammar, idioms, and advanced vocabulary.',
          previewText:
              'THE OFFICIAL IELTS PREPARATION COMPENDIUM\n\nChapter 1: Academic Vocabulary Band 7 to 9\nChapter 2: Paraphrasing & Collocation Masterclass\nChapter 3: Grammar for IELTS: Complex Sentences & Passive Voice\nChapter 4: Common Pitfalls and Avoidable Errors.',
        ),
        LmsResource(
          id: 'res-ielts-3',
          title: 'IELTS All Module Presentation',
          type: 'Presentation',
          fileSize: '18.7 MB',
          pages: 85,
          description: 'Master slides covering band 8+ strategies for Reading, Listening, Writing, and Speaking.',
          previewText:
              'IELTS MASTERCLASS SLIDES\n\nSlide 1: IELTS Test Format & Scoring System\nSlide 2: Reading Question Types: T/F/NG, Headings, Matching\nSlide 3: Listening Traps & Distractors\nSlide 4: Writing Task 1 Overview Formats\nSlide 5: Writing Task 2 Four-Paragraph Architecture\nSlide 6: Speaking Part 2 Storytelling Structure.',
        ),
        LmsResource(
          id: 'res-ielts-4',
          title: 'IELTS Study Material',
          type: 'Study Material',
          fileSize: '9.4 MB',
          pages: 92,
          description: 'High-frequency topic vocabulary lists, linking words, essay templates, and speaking cue card answers.',
          previewText:
              'ESSENTIAL IELTS STUDY MATERIAL & CHEAT SHEETS\n\n- Linking Devices: Furthermore, In contrast, Consequently, Notwithstanding\n- Task 1 Vocab: Surge, Plummet, Fluctuate, Plateau, Steep rise\n- Task 2 Topics: Education, Technology, Environment, Health, Globalization\n- Speaking Cue Card Formula: Past Experience + Present Impact + Future Plan.',
        ),
      ],
      discussions: [
        LmsDiscussion(
          id: 'disc-ielts-1',
          studentName: 'Hamza Tariq',
          studentAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
          date: '1 day ago',
          topic: 'True / False / Not Given vs Yes / No / Not Given',
          question: 'What is the exact distinction between True/False/Not Given and Yes/No/Not Given questions in IELTS Reading?',
          upvotes: 14,
          answers: [
            DiscussionAnswer(
              id: 'ans-ielts-1',
              authorName: 'Madam Ayesha Khan',
              isInstructor: true,
              date: '18 hours ago',
              answerText:
                  'True/False/Not Given deals with factual information in the text, whereas Yes/No/Not Given deals with the writer\'s opinions, views, or claims. Make sure to write the exact letters requested on the answer sheet!',
              upvotes: 21,
            ),
          ],
        ),
      ],
      modules: [
        // Module 1: Reading
        LmsModule(
          id: 'ielts-mod-1',
          courseId: 'course-ielts',
          moduleNumber: 1,
          title: 'Reading',
          description: 'Skimming, scanning, True/False/Not Given, paragraph headings, and time management for academic texts.',
          duration: '10 Hours',
          isUnlocked: true,
          progress: 1.0,
          resources: [
            LmsResource(
              id: 'ielts-m1-r1',
              title: 'Academic Reading Speed Techniques Guide',
              type: 'PDF',
              fileSize: '2.1 MB',
              pages: 28,
              description: 'Strategies for solving 40 questions in 60 minutes with 90%+ accuracy.',
              previewText: 'Key Strategy: Read questions first, underline keywords, and scan for synonyms in the text.',
            ),
          ],
          quizzes: [
            LmsQuizRef(
              id: 'ielts-quiz-1',
              title: 'Reading Practice Test 1 (Passage 1 & 2)',
              questionCount: 20,
              timeLimitMinutes: 30,
              passingScore: 75,
              isCompleted: true,
              userScore: 90,
            ),
          ],
          assessmentTest: LmsAssessmentRef(
            id: 'ielts-asst-1',
            title: 'Full Reading Mock Test (40 Questions)',
            totalMarks: 40,
            timeLimitMinutes: 60,
            dueDate: '2026-10-18',
            isUnlocked: true,
            isSubmitted: true,
            scoredMarks: 36,
          ),
          lectures: [
            LmsLecture(
              id: 'ielts-lec-101',
              moduleId: 'ielts-mod-1',
              lectureNumber: 1,
              title: 'Introduction to Academic Reading & Question Types',
              duration: '25 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Overview of the 3 reading passages, difficulty gradient, and scoring band conversion.',
              transcript: 'Welcome to the IELTS Academic Reading module. Today we analyze the layout of the 3 passages...',
              notes: [],
              resources: [],
            ),
            LmsLecture(
              id: 'ielts-lec-102',
              moduleId: 'ielts-mod-1',
              lectureNumber: 2,
              title: 'Mastering True / False / Not Given & Yes / No / Not Given',
              duration: '32 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Step-by-step methodology to eliminate False vs Not Given confusion.',
              transcript: 'The single biggest challenge students face is distinguishing between False and Not Given...',
              notes: [],
              resources: [],
            ),
            LmsLecture(
              id: 'ielts-lec-103',
              moduleId: 'ielts-mod-1',
              lectureNumber: 3,
              title: 'Matching Headings & Information to Paragraphs',
              duration: '28 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Finding main ideas in topic sentences and avoiding distractor keywords.',
              transcript: 'Matching headings requires grasping the central theme of each paragraph rather than matching isolated words...',
              notes: [],
              resources: [],
            ),
          ],
        ),

        // Module 2: Listening
        LmsModule(
          id: 'ielts-mod-2',
          courseId: 'course-ielts',
          moduleNumber: 2,
          title: 'Listening',
          description: 'Section 1 to 4 audio mastery, handling distractors, spelling rules, map labeling, and multiple-choice questions.',
          duration: '10 Hours',
          isUnlocked: true,
          progress: 0.80,
          resources: [
            LmsResource(
              id: 'ielts-m2-r1',
              title: 'IELTS Listening Accent & Spelling Handbook',
              type: 'PDF',
              fileSize: '3.4 MB',
              pages: 35,
              description: 'Guide to British numbers, letters, names, and phonetic traps.',
              previewText: 'Common spelling traps: Double letters (Accommodate, Millennium), Silent letters, and date formats.',
            ),
          ],
          quizzes: [
            LmsQuizRef(
              id: 'ielts-quiz-2',
              title: 'Listening Sections 1 & 2 Audio Quiz',
              questionCount: 20,
              timeLimitMinutes: 25,
              passingScore: 75,
              isCompleted: true,
              userScore: 85,
            ),
          ],
          assessmentTest: LmsAssessmentRef(
            id: 'ielts-asst-2',
            title: 'Full Timed Listening Mock Test (4 Sections)',
            totalMarks: 40,
            timeLimitMinutes: 40,
            dueDate: '2026-10-22',
            isUnlocked: true,
            isSubmitted: false,
          ),
          lectures: [
            LmsLecture(
              id: 'ielts-lec-201',
              moduleId: 'ielts-mod-2',
              lectureNumber: 1,
              title: 'Listening Section 1: Form Completion & Numbers',
              duration: '22 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Handling everyday transactional dialogues, phone numbers, postcodes, and names.',
              transcript: 'Section 1 is a conversation between two people in an everyday social context...',
              notes: [],
              resources: [],
            ),
            LmsLecture(
              id: 'ielts-lec-202',
              moduleId: 'ielts-mod-2',
              lectureNumber: 2,
              title: 'Listening Section 2 & 3: Maps, Diagrams & Group Discussions',
              duration: '30 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Directional vocabulary, navigating plans and maps, and tracking multi-speaker university conversations.',
              transcript: 'In map labeling, orient yourself with the compass rose and key starting landmarks immediately...',
              notes: [],
              resources: [],
            ),
          ],
        ),

        // Module 3: Writing
        LmsModule(
          id: 'ielts-mod-3',
          courseId: 'course-ielts',
          moduleNumber: 3,
          title: 'Writing',
          description: 'Task 1 visual summaries (Charts, Graphs, Maps, Processes) and Task 2 academic essays (Agree/Disagree, Discuss Both Views).',
          duration: '10 Hours',
          isUnlocked: true,
          progress: 0.40,
          resources: [
            LmsResource(
              id: 'ielts-m3-r1',
              title: 'Band 9 Essay Templates & Vocabulary Matrix',
              type: 'PDF',
              fileSize: '4.2 MB',
              pages: 42,
              description: 'Complete structure for all 5 essay types with high-scoring sample essays.',
              previewText: 'Introduction: Paraphrase question prompt + Thesis statement + Outline sentence.',
            ),
          ],
          quizzes: [
            LmsQuizRef(
              id: 'ielts-quiz-3',
              title: 'Writing Task 1 Overview & Vocab Quiz',
              questionCount: 15,
              timeLimitMinutes: 20,
              passingScore: 75,
              isCompleted: false,
            ),
          ],
          assessmentTest: LmsAssessmentRef(
            id: 'ielts-asst-3',
            title: 'Full Writing Assessment (Task 1 + Task 2)',
            totalMarks: 9,
            timeLimitMinutes: 60,
            dueDate: '2026-10-29',
            isUnlocked: true,
            isSubmitted: false,
          ),
          lectures: [
            LmsLecture(
              id: 'ielts-lec-301',
              moduleId: 'ielts-mod-3',
              lectureNumber: 1,
              title: 'Task 1: Line Graphs, Bar Charts & Pie Charts',
              duration: '35 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Structuring the 150-word report: Introduction, Overview paragraph, and two detailed data body paragraphs.',
              transcript: 'The overview is the single most critical paragraph in Task 1. Without an overview, you cannot score above Band 5...',
              notes: [],
              resources: [],
            ),
            LmsLecture(
              id: 'ielts-lec-302',
              moduleId: 'ielts-mod-3',
              lectureNumber: 2,
              title: 'Task 2: Opinion & Discussion Essay Structures',
              duration: '38 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=500&auto=format&fit=crop&q=80',
              isCompleted: false,
              overview: 'Developing fully extended ideas, cohesive devices, and avoiding memorized clichés.',
              transcript: 'In Task 2, examiners look for Task Achievement, Coherence & Cohesion, Lexical Resource, and Grammatical Range...',
              notes: [],
              resources: [],
            ),
          ],
        ),

        // Module 4: Speaking
        LmsModule(
          id: 'ielts-mod-4',
          courseId: 'course-ielts',
          moduleNumber: 4,
          title: 'Speaking',
          description: 'Part 1 Interview, Part 2 Long Turn Cue Card, and Part 3 Two-way Discussion strategies with pronunciation and fluency drills.',
          duration: '10 Hours',
          isUnlocked: true,
          progress: 0.15,
          resources: [
            LmsResource(
              id: 'ielts-m4-r1',
              title: 'Speaking Cue Cards & Topic Predictor 2026',
              type: 'PDF',
              fileSize: '5.1 MB',
              pages: 56,
              description: 'Latest cue cards with high-band model answers and examiner follow-up questions.',
              previewText: 'Part 2 Strategy: Use the 1-minute prep time to jot down 4 keywords corresponding to each bullet point.',
            ),
          ],
          quizzes: [
            LmsQuizRef(
              id: 'ielts-quiz-4',
              title: 'Speaking Idioms & Discourse Markers Check',
              questionCount: 15,
              timeLimitMinutes: 20,
              passingScore: 75,
              isCompleted: false,
            ),
          ],
          assessmentTest: LmsAssessmentRef(
            id: 'ielts-asst-4',
            title: 'Mock Speaking Interview Assessment',
            totalMarks: 9,
            timeLimitMinutes: 15,
            dueDate: '2026-11-04',
            isUnlocked: true,
            isSubmitted: false,
          ),
          lectures: [
            LmsLecture(
              id: 'ielts-lec-401',
              moduleId: 'ielts-mod-4',
              lectureNumber: 1,
              title: 'Speaking Part 1: Fluency & Natural Responses',
              duration: '26 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=500&auto=format&fit=crop&q=80',
              isCompleted: false,
              overview: 'Giving 2-3 sentence expanded answers without stalling or overthinking.',
              transcript: 'Part 1 tests your ability to give conversational answers on familiar topics such as hobbies, hometown, and studies...',
              notes: [],
              resources: [],
            ),
            LmsLecture(
              id: 'ielts-lec-402',
              moduleId: 'ielts-mod-4',
              lectureNumber: 2,
              title: 'Speaking Part 2 & 3: Master the 2-Minute Monologue',
              duration: '32 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=500&auto=format&fit=crop&q=80',
              isCompleted: false,
              overview: 'Structuring your cue card talk like a story and answering abstract philosophical questions in Part 3.',
              transcript: 'To speak fluently for 2 minutes in Part 2, structure your response chronologically: context, narrative, and personal reflection...',
              notes: [],
              resources: [],
            ),
          ],
        ),
      ],
    ),

    // Course 2: CIT Prep
    LmsCourse(
      id: 'course-cit',
      title: 'CIT Prep - Certified Instructional Trainer',
      category: 'Professional Certification',
      level: 'Advanced',
      thumbnailUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&auto=format&fit=crop&q=80',
      rating: 4.9,
      ratingCount: 342,
      studentsCount: 1280,
      progress: 0.68,
      instructorName: 'Dr. John Doe, CIT Master',
      instructorRole: 'Lead Instructor & Board Certified Trainer',
      instructorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      instructorEmail: 'john.doe@hexalabes.com',
      duration: '45 Hours',
      modulesCount: 4,
      lecturesCount: 16,
      isCertified: true,
      hasScorm: false,
      courseFee: 45000,
      isEnrolled: true,
      description:
          'Comprehensive preparation for the Board of Certified Safety Professionals (BCSP) Certified Instructional Trainer (CIT) examination. Covers adult learning theory, training needs assessment, curriculum design, classroom delivery, and instructional evaluation.',
      whatYouWillLearn: [
        'Adult learning principles and instructional design methodologies',
        'Effective presentation techniques and interactive training delivery',
        'Designing valid assessments, rubrics, and feedback mechanisms',
        'Digital simulations and contemporary corporate learning tools',
        'Full mock exams aligned with BCSP CIT blueprint guidelines',
      ],
      requirements: [
        'Basic familiarity with instructional design or corporate training',
        'No prior certification required, open to all safety and education professionals',
      ],
      resources: [
        LmsResource(
          id: 'res-cit-1',
          title: 'CIT Exam Blueprint & Reference Guide 2026',
          type: 'PDF',
          fileSize: '4.8 MB',
          pages: 64,
          description: 'Official BCSP CIT Examination blueprint with domain percentages and sample question types.',
          previewText:
              'DOMAIN 1: Training Needs Assessment and Analysis (22%)\nDOMAIN 2: Instructional Development and Design (28%)\nDOMAIN 3: Training Delivery and Facilitation (32%)\nDOMAIN 4: Evaluation and Assessment (18%)\n\nKey Concepts:\n- Andragogy vs Pedagogy\n- Blooms Taxonomy for Cognitive Domain\n- Kirkpatricks Four-Level Evaluation Model',
        ),
        LmsResource(
          id: 'res-cit-2',
          title: 'Adult Learning Theories & Andragogy Handout',
          type: 'Study Material',
          fileSize: '2.4 MB',
          pages: 32,
          description: 'In-depth notes on Malcolm Knowles adult learning assumptions and experiential learning cycles.',
          previewText:
              'Malcolm Knowles identified 6 core assumptions about adult learners:\n1. Need to Know: Adults need to understand why they must learn something.\n2. Self-Concept: Adults have a self-concept of being responsible for their decisions.\n3. Prior Experience: Adult learners bring diverse life experience to training.\n4. Readiness to Learn: Adults become ready to learn when they experience a need to cope.\n5. Orientation to Learning: Life-centered, task-centered, or problem-centered.\n6. Motivation: Internal motivators (self-esteem, job satisfaction) dominate.',
        ),
        LmsResource(
          id: 'res-cit-3',
          title: 'Instructional Design Presentation Slides',
          type: 'Presentation',
          fileSize: '12.1 MB',
          pages: 45,
          description: 'Slide deck covering ADDIE model and rapid instructional prototyping.',
          previewText: 'Slide 1: Overview of ADDIE Model (Analysis, Design, Development, Implementation, Evaluation)\nSlide 2: Conducting Needs Analysis\nSlide 3: Writing SMART Learning Objectives\nSlide 4: Formative vs Summative Evaluation',
        ),
      ],
      discussions: [
        LmsDiscussion(
          id: 'disc-cit-1',
          studentName: 'Khalid Ahmed',
          studentAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
          date: '2 days ago',
          topic: 'Module 2: Blooms Taxonomy in Safety Exams',
          question: 'In the CIT exam, how does BCSP distinguish between Analyze and Evaluate level questions for emergency protocols?',
          upvotes: 8,
          answers: [
            DiscussionAnswer(
              id: 'ans-1',
              authorName: 'Dr. John Doe, CIT Master',
              isInstructor: true,
              date: '1 day ago',
              answerText:
                  'Great question Khalid! Analyze level questions test your ability to break down incident reports into root causes. Evaluate questions require you to make a judgment between competing corrective action plans based on OSHA criteria.',
              upvotes: 12,
            ),
          ],
        ),
      ],
      modules: [
        LmsModule(
          id: 'cit-mod-1',
          courseId: 'course-cit',
          moduleNumber: 1,
          title: 'Adult Learning Theory & Training Assessment',
          description: 'Understanding adult learner psychology, learning styles, and conducting organizational needs assessments.',
          duration: '10 Hours',
          isUnlocked: true,
          progress: 1.0,
          resources: [
            LmsResource(
              id: 'cit-m1-r1',
              title: 'Module 1 Study Guide',
              type: 'PDF',
              fileSize: '1.8 MB',
              pages: 20,
              description: 'Comprehensive study guide for adult learning principles and needs assessment.',
              previewText: 'Key topics: Needs Assessment surveys, Gap Analysis, Malcolm Knowles andragogical model.',
            ),
          ],
          quizzes: [
            LmsQuizRef(
              id: 'cit-quiz-1',
              title: 'Module 1 Checkpoint Quiz',
              questionCount: 15,
              timeLimitMinutes: 20,
              passingScore: 75,
              isCompleted: true,
              userScore: 93,
            ),
          ],
          assessmentTest: LmsAssessmentRef(
            id: 'cit-asst-1',
            title: 'Module 1 Comprehensive Assessment',
            totalMarks: 50,
            timeLimitMinutes: 45,
            dueDate: '2026-10-15',
            isUnlocked: true,
            isSubmitted: true,
            scoredMarks: 47,
          ),
          lectures: [
            LmsLecture(
              id: 'cit-lec-101',
              moduleId: 'cit-mod-1',
              lectureNumber: 1,
              title: 'Introduction to CIT & Certification Standards',
              duration: '22 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Welcome to the CIT certification course. In this video, we review BCSP standards, examination blueprints, and exam day requirements.',
              transcript: 'Hello everyone and welcome to the Certified Instructional Trainer preparation course. In this initial lecture we establish our roadmap...',
              notes: [
                LectureNote(id: 'n1', timestamp: '04:15', content: 'BCSP requires recertification every 5 years.', createdAt: DateTime.now().subtract(const Duration(days: 3))),
              ],
              resources: [],
            ),
            LmsLecture(
              id: 'cit-lec-102',
              moduleId: 'cit-mod-1',
              lectureNumber: 2,
              title: 'Malcolm Knowles Andragogy vs Pedagogy',
              duration: '28 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Core principles of adult learning: self-direction, experience integration, problem-oriented learning.',
              transcript: 'Adult learners possess intrinsic motivation and rely on accumulated experience...',
              notes: [],
              resources: [],
            ),
          ],
        ),
        LmsModule(
          id: 'cit-mod-2',
          courseId: 'course-cit',
          moduleNumber: 2,
          title: 'Instructional Design & Course Development',
          description: 'Writing behavioral objectives, structuring curriculum, developing multimedia handouts, and lesson planning.',
          duration: '12 Hours',
          isUnlocked: true,
          progress: 0.75,
          resources: [
            LmsResource(
              id: 'cit-m2-r1',
              title: 'Blooms Taxonomy Action Verbs Quick Reference',
              type: 'Handout',
              fileSize: '1.2 MB',
              pages: 4,
              description: 'Chart of action verbs categorized across all 6 cognitive domain levels.',
              previewText: 'Remembering, Understanding, Applying, Analyzing, Evaluating, Creating.',
            ),
          ],
          quizzes: [
            LmsQuizRef(
              id: 'cit-quiz-2',
              title: 'Instructional Design Mastery Quiz',
              questionCount: 20,
              timeLimitMinutes: 25,
              passingScore: 80,
              isCompleted: true,
              userScore: 88,
            ),
          ],
          assessmentTest: LmsAssessmentRef(
            id: 'cit-asst-2',
            title: 'Module 2 Assessment Test: Lesson Plan Design',
            totalMarks: 50,
            timeLimitMinutes: 60,
            dueDate: '2026-10-20',
            isUnlocked: true,
            isSubmitted: false,
          ),
          lectures: [
            LmsLecture(
              id: 'cit-lec-201',
              moduleId: 'cit-mod-2',
              lectureNumber: 1,
              title: 'The ADDIE Model for Training Programs',
              duration: '32 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Deep dive into every phase of ADDIE and how corporate safety programs utilize iterative prototyping.',
              transcript: 'Today we break down the five phases of the ADDIE process...',
              notes: [],
              resources: [],
            ),
          ],
        ),
        LmsModule(
          id: 'cit-mod-3',
          courseId: 'course-cit',
          moduleNumber: 3,
          title: 'Training Delivery, Facilitation & Classroom Management',
          description: 'Mastering presentation skills, handling difficult questions, small group exercises, and virtual classroom delivery.',
          duration: '11 Hours',
          isUnlocked: true,
          progress: 0.33,
          resources: [],
          quizzes: [],
          lectures: [
            LmsLecture(
              id: 'cit-lec-301',
              moduleId: 'cit-mod-3',
              lectureNumber: 1,
              title: 'Vocal Dynamics, Body Language & Platform Presence',
              duration: '30 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Techniques for command of the classroom, active listening, and managing presentation anxiety.',
              transcript: 'Body language accounts for over half of perceived confidence in a classroom setting...',
              notes: [],
              resources: [],
            ),
          ],
        ),
        LmsModule(
          id: 'cit-mod-4',
          courseId: 'course-cit',
          moduleNumber: 4,
          title: 'Evaluation, Assessment & Continuous Improvement',
          description: 'Kirkpatricks 4-level evaluation, return on investment (ROI) calculations, item analysis for test questions.',
          duration: '12 Hours',
          isUnlocked: true,
          progress: 0.0,
          resources: [],
          quizzes: [],
          lectures: [
            LmsLecture(
              id: 'cit-lec-401',
              moduleId: 'cit-mod-4',
              lectureNumber: 1,
              title: 'Kirkpatricks Four Levels of Training Evaluation',
              duration: '35 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=500&auto=format&fit=crop&q=80',
              isCompleted: false,
              overview: 'Measuring Reaction, Learning, Behavior, and Organizational Business Results.',
              transcript: 'Donald Kirkpatrick revolutionized training assessment...',
              notes: [],
              resources: [],
            ),
          ],
        ),
      ],
    ),

    // Course 3: IOSH Managing Safely
    LmsCourse(
      id: 'course-iosh',
      title: 'IOSH Managing Safely V5.0',
      category: 'Health & Safety Management',
      level: 'Intermediate',
      thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
      rating: 4.85,
      ratingCount: 210,
      studentsCount: 890,
      progress: 0.85,
      instructorName: 'Sarah Jenkins, CMIOSH',
      instructorRole: 'Chartered Safety Consultant',
      instructorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
      instructorEmail: 'sarah.jenkins@hexalabes.com',
      duration: '30 Hours',
      modulesCount: 4,
      lecturesCount: 16,
      isCertified: true,
      hasScorm: false,
      courseFee: 38000,
      isEnrolled: true,
      description:
          'Globally recognized certificate by the Institution of Occupational Safety and Health (IOSH). Designed for managers and supervisors in any sector to understand practical actions required to handle health and safety in their teams.',
      whatYouWillLearn: [
        'Assessing and controlling risks in workplace environments',
        'Understanding manager health & safety legal responsibilities',
        'Identifying common hazards (Fire, Electricity, Chemicals, Work at Height)',
        'Investigating accidents and incidents to prevent reoccurrence',
      ],
      requirements: ['No previous health and safety knowledge required.'],
      resources: [
        LmsResource(
          id: 'res-iosh-1',
          title: 'IOSH Managing Safely V5.0 Course Book PDF',
          type: 'Book',
          fileSize: '18.4 MB',
          pages: 140,
          description: 'Official comprehensive study text for IOSH Managing Safely.',
          previewText: 'Module 1: Introducing Managing Safely\nModule 2: Assessing Risks\nModule 3: Controlling Risks\nModule 4: Understanding Responsibilities.',
        ),
      ],
      discussions: [],
      modules: [
        LmsModule(
          id: 'iosh-mod-1',
          courseId: 'course-iosh',
          moduleNumber: 1,
          title: 'Introducing Managing Safely & Risk Assessment',
          description: 'The moral, legal, and financial reasons for managing safety and the 5-step risk assessment method.',
          duration: '6 Hours',
          isUnlocked: true,
          progress: 1.0,
          resources: [],
          quizzes: [
            LmsQuizRef(
              id: 'iosh-quiz-1',
              title: 'Risk Assessment Quiz',
              questionCount: 10,
              timeLimitMinutes: 15,
              passingScore: 80,
              isCompleted: true,
              userScore: 100,
            ),
          ],
          lectures: [
            LmsLecture(
              id: 'iosh-lec-1',
              moduleId: 'iosh-mod-1',
              lectureNumber: 1,
              title: 'The Moral, Legal & Financial Case for Safety',
              duration: '20 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Why managers must manage health and safety: moral duty of care, criminal/civil penalties, and accident costs.',
              transcript: 'Health and safety management starts with understanding the three drivers: Moral, Legal, and Financial reasons...',
              notes: [],
              resources: [],
            ),
          ],
        ),
        LmsModule(
          id: 'iosh-mod-2',
          courseId: 'course-iosh',
          moduleNumber: 2,
          title: 'Controlling Workplace Risks',
          description: 'Hierarchy of risk control, safe systems of work, and personal protective equipment (PPE).',
          duration: '8 Hours',
          isUnlocked: true,
          progress: 0.7,
          resources: [],
          quizzes: [],
          lectures: [
            LmsLecture(
              id: 'iosh-lec-2',
              moduleId: 'iosh-mod-2',
              lectureNumber: 1,
              title: 'Hierarchy of Risk Controls (ERICPD)',
              duration: '24 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Eliminate, Reduce, Isolate, Control, PPE, Discipline.',
              transcript: 'When deciding how to control a risk, always apply the hierarchy in order...',
              notes: [],
              resources: [],
            ),
          ],
        ),
      ],
    ),

    // Course 4: Web Development
    LmsCourse(
      id: 'course-webdev',
      title: 'Web Development (Full Stack MERN)',
      category: 'Computer Science & Software',
      level: 'All Levels',
      thumbnailUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&auto=format&fit=crop&q=80',
      rating: 4.92,
      ratingCount: 512,
      studentsCount: 2340,
      progress: 0.72,
      instructorName: 'Engr. M. Farooq',
      instructorRole: 'Principal Full Stack Architect',
      instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      instructorEmail: 'farooq@hexalabes.com',
      duration: '60 Hours',
      modulesCount: 4,
      lecturesCount: 24,
      isCertified: true,
      hasScorm: false,
      courseFee: 40000,
      isEnrolled: true,
      description: 'Master modern frontend and backend web development using React, Node.js, Express, MongoDB, RESTful APIs, and deployment pipelines.',
      whatYouWillLearn: [
        'Responsive UI Design with HTML5, Modern CSS, Grid & Tailwind',
        'Modern JavaScript (ES6+, Async/Await, Closures, DOM)',
        'React 18 Architecture: Hooks, Redux Toolkit, Context API',
        'Backend Development with Node.js, Express, and JWT Authentication',
      ],
      requirements: ['Basic computer literacy. No programming experience required.'],
      resources: [
        LmsResource(
          id: 'res-wd-1',
          title: 'Full Stack MERN Architecture Cheatsheet',
          type: 'Handout',
          fileSize: '3.5 MB',
          pages: 30,
          description: 'Quick reference for React hooks, Express routing, and MongoDB query operators.',
          previewText: 'React Hooks: useState, useEffect, useContext, useMemo, useCallback, useRef.',
        ),
      ],
      discussions: [],
      modules: [
        LmsModule(
          id: 'wd-mod-1',
          courseId: 'course-webdev',
          moduleNumber: 1,
          title: 'Modern Frontend Fundamentals (HTML5 & Modern CSS)',
          description: 'Semantic markup, Flexbox, Grid systems, and building responsive layouts.',
          duration: '8 Hours',
          isUnlocked: true,
          progress: 1.0,
          resources: [],
          quizzes: [],
          lectures: [
            LmsLecture(
              id: 'wd-lec-1',
              moduleId: 'wd-mod-1',
              lectureNumber: 1,
              title: 'HTML5 Semantic Tags & Accessibility Best Practices',
              duration: '25 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Structure web pages with header, nav, main, section, article, and footer tags.',
              transcript: 'In this lecture we explore semantic HTML5 elements that improve SEO and accessibility...',
              notes: [],
              resources: [],
            ),
          ],
        ),
        LmsModule(
          id: 'wd-mod-2',
          courseId: 'course-webdev',
          moduleNumber: 2,
          title: 'JavaScript ES6+ & Async Programming',
          description: 'Arrow functions, Promises, Async/Await, Fetch API, and DOM manipulation.',
          duration: '12 Hours',
          isUnlocked: true,
          progress: 0.8,
          resources: [],
          quizzes: [],
          lectures: [
            LmsLecture(
              id: 'wd-lec-2',
              moduleId: 'wd-mod-2',
              lectureNumber: 1,
              title: 'Modern JavaScript: Promises & Async/Await',
              duration: '30 mins',
              videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
              previewThumbnail: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=500&auto=format&fit=crop&q=80',
              isCompleted: true,
              overview: 'Handling asynchronous operations, error catching, and API integrations.',
              transcript: 'Promises and Async/Await allow writing clean non-blocking code in JavaScript...',
              notes: [],
              resources: [],
            ),
          ],
        ),
      ],
    ),
  ];

  static LmsCourse getCourseById(String id) {
    return courses.firstWhere(
      (c) => c.id == id,
      orElse: () => courses.first,
    );
  }
}
